# Regression Example in Keras
Predicting house prices in Boston, Massachusetts 

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/the-deep-learners/deep-learning-illustrated/blob/master/notebooks/regression_in_keras.ipynb)

#### Load dependencies

In [5]:
import numpy as np
from keras.datasets import boston_housing
from keras.models import Sequential
from keras.layers import Dense, Dropout 
from keras.layers.normalization import BatchNormalization 

#### Load data

In [6]:
(X_train, y_train), (X_valid, y_valid) = boston_housing.load_data()

Exception: URL fetch failure on https://storage.googleapis.com/tensorflow/tf-keras-datasets/boston_housing.npz: None -- [Errno 11001] getaddrinfo failed

In [6]:
X_train.shape

(404, 13)

In [7]:
X_valid.shape

(102, 13)

In [3]:
X_train[0]

array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
        91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
        18.72   ])

In [4]:
y_train[0]

15.2

#### Design neural network architecture

In [8]:
model = Sequential()

model.add(Dense(32, input_dim=13, activation='relu'))
model.add(BatchNormalization())

model.add(Dense(16, activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.2))

model.add(Dense(1, activation='linear'))

In [9]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 32)                448       
_________________________________________________________________
batch_normalization_1 (Batch (None, 32)                128       
_________________________________________________________________
dense_2 (Dense)              (None, 16)                528       
_________________________________________________________________
batch_normalization_2 (Batch (None, 16)                64        
_________________________________________________________________
dropout_1 (Dropout)          (None, 16)                0         
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 17        
Total params: 1,185
Trainable params: 1,089
Non-trainable params: 96
_________________________________________________________________


#### Configure Model

In [10]:
model.compile(loss='mean_squared_error', optimizer='adam')

#### Train!

In [12]:
model.fit(X_train, y_train, 
          batch_size=8, epochs=32, verbose=1, 
          validation_data=(X_valid, y_valid))

Train on 404 samples, validate on 102 samples
Epoch 1/32
404/404 [==============================] - 0s 299us/step - loss: 49.2080 - val_loss: 56.6020
Epoch 2/32
404/404 [==============================] - 0s 271us/step - loss: 47.4038 - val_loss: 29.8796
Epoch 3/32
404/404 [==============================] - 0s 197us/step - loss: 46.7576 - val_loss: 23.9344
Epoch 4/32
404/404 [==============================] - 0s 187us/step - loss: 44.1485 - val_loss: 42.2967
Epoch 5/32
404/404 [==============================] - 0s 164us/step - loss: 49.0559 - val_loss: 46.9688
Epoch 6/32
404/404 [==============================] - 0s 162us/step - loss: 43.6892 - val_loss: 33.0174
Epoch 7/32
404/404 [==============================] - 0s 148us/step - loss: 47.0792 - val_loss: 54.1364
Epoch 8/32
404/404 [==============================] - 0s 153us/step - loss: 50.8361 - val_loss: 36.3195
Epoch 9/32
404/404 [==============================] - 0s 149us/step - loss: 40.6915 - val_loss: 29.8989
Epoch 10/32
404/40

In [14]:
X_valid[42]

array([  9.32909,   0.     ,  18.1    ,   0.     ,   0.713  ,   6.185  ,
        98.7    ,   2.2616 ,  24.     , 666.     ,  20.2    , 396.9    ,
        18.13   ])

In [13]:
y_valid[42]

14.1

In [17]:
model.predict(np.reshape(X_valid[42], [1, 13]))

array([[20.880333]], dtype=float32)